

# This file was *autogenerated* from the file ornekModel.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_90 = Integer(90); _sage_const_40 = Integer(40); _sage_const_30 = Integer(30)
p = MixedIntegerLinearProgram (maximization=True, solver = "GLPK", names=('x1',)); (x1,) = p._first_ngens(1)

p.set_binary (x1)



p.add_constraint(_sage_const_2 *x1[_sage_const_0 ] + x1[_sage_const_1 ] <= _sage_const_100 )
p.add_constraint(x1[_sage_const_0 ] + _sage_const_3 *x1[_sage_const_1 ] <= _sage_const_90 )
p.add_constraint(x1[_sage_const_0 ] >= _sage_const_1 )
p.add_constraint(x1[_sage_const_1 ] >= _sage_const_0 )

p.set_objective(_sage_const_40 *x1[_sage_const_0 ]+ _sage_const_30 *x1[_sage_const_1 ])

print(p.solve())

